on:
  workflow_dispatch:

env:
  JEKYLL_ENV: ${{ vars.JEKYLL_ENV }}
  NODE_ENV: ${{ vars.NODE_ENV }}

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - run: npm install --include dev

      - name: Build the site in the jekyll/builder container
        run: |
          docker run \
          -v ${{ github.workspace }}:/srv/jekyll -v ${{ github.workspace }}/_site:/srv/jekyll/_site \
          jekyll/builder:latest /bin/bash -c "chmod -R 777 /srv/jekyll && \
          NODE_ENV=$NODE_ENV jekyll build --future --trace"

      - uses: crazy-max/ghaction-github-pages@v4.1.0
        with:
          target_branch: main
          build_dir: _site/
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
